services:
  speech-recognizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speech-recognizer
    volumes:
      - .:/app
      - audio_data:/app/audio_files
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - NAME_BOT=${NAME_BOT}
      - API_KEY=${API_KEY}
      - HF_TOKEN=${HF_TOKEN}
    command: python main.py
    restart: unless-stopped

volumes:
  audio_data:
